import { expect, test, type Page } from '@playwright/test'

const panel = (page: Page) => page.getByRole('dialog', { name: 'Timer', exact: true })
const readout = (page: Page) => panel(page).locator('.time-display')
const trigger = (page: Page) => page.getByRole('button', { name: 'Timer', exact: true })

test.beforeEach(async ({ page }) => {
  await page.goto('./')
  await expect(page.getByRole('textbox', { name: 'Text editor' })).toBeVisible()
  await page.clock.install()
  await trigger(page).click()
})

test('stopwatch continues with panel closed, pauses, resumes and resets', async ({ page }) => {
  await panel(page).getByRole('button', { name: 'Start', exact: true }).click()
  await expect(panel(page).getByRole('button', { name: 'Pause', exact: true })).toBeFocused()
  await page.clock.runFor(3200)
  await expect(readout(page)).toHaveText('00:03')
  await page.keyboard.press('Escape')
  await expect(trigger(page)).toBeFocused()
  await page.clock.runFor(5000)
  await trigger(page).click()
  await expect(readout(page)).toHaveText('00:08')
  await panel(page).getByRole('button', { name: 'Pause', exact: true }).click()
  await expect(panel(page).getByRole('button', { name: 'Resume', exact: true })).toBeFocused()
  await page.clock.runFor(3000)
  await expect(readout(page)).toHaveText('00:08')
  await panel(page).getByRole('button', { name: 'Resume', exact: true }).click()
  await page.clock.runFor(2000)
  await expect(readout(page)).toHaveText('00:10')
  await panel(page).getByRole('button', { name: 'Reset', exact: true }).click()
  await expect(readout(page)).toHaveText('00:00')
})

test('countdown uses chosen duration, resumes remaining time, and finishes while closed', async ({ page }) => {
  await panel(page).getByRole('button', { name: 'Countdown', exact: true }).click()
  await page.getByLabel('Minutes', { exact: true }).fill('0')
  await page.getByLabel('Seconds', { exact: true }).fill('10')
  await panel(page).getByRole('button', { name: 'Start', exact: true }).click()
  await page.clock.runFor(3000)
  await expect(readout(page)).toHaveText('00:07')
  await panel(page).getByRole('button', { name: 'Pause', exact: true }).click()
  await page.clock.runFor(5000)
  await expect(readout(page)).toHaveText('00:07')
  await panel(page).getByRole('button', { name: 'Resume', exact: true }).click()
  await page.keyboard.press('Escape')
  // Jump past the deadline without replaying every interval: background tabs may be throttled.
  await page.clock.fastForward(60000)
  await expect(page.locator('.timer-completion')).toBeVisible()
  await trigger(page).click()
  await expect(readout(page)).toHaveText('00:00')
  await panel(page).getByRole('button', { name: 'Reset', exact: true }).click()
  await expect(readout(page)).toHaveText('00:10')
  await expect(page.getByLabel('Seconds', { exact: true })).toBeEnabled()
  await expect(page.locator('.timer-completion')).toBeHidden()
})

test('countdown rejects zero and invalid seconds and fits on a phone', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 740 })
  await panel(page).getByRole('button', { name: 'Countdown', exact: true }).click()
  await page.getByLabel('Minutes', { exact: true }).fill('0')
  await page.getByLabel('Seconds', { exact: true }).fill('0')
  await expect(panel(page).getByRole('button', { name: 'Start', exact: true })).toBeDisabled()
  await page.getByLabel('Seconds', { exact: true }).fill('60')
  await expect(panel(page).getByRole('button', { name: 'Start', exact: true })).toBeDisabled()
  await page.getByLabel('Seconds', { exact: true }).fill('30')
  await expect(panel(page).getByRole('button', { name: 'Start', exact: true })).toBeEnabled()
  const box = await panel(page).boundingBox()
  expect(box!.x).toBeGreaterThanOrEqual(0)
  expect(box!.x + box!.width).toBeLessThanOrEqual(375)
  expect(await page.getByLabel('Minutes', { exact: true }).evaluate(el => getComputedStyle(el).fontSize)).toBe('16px')
  await page.keyboard.press('Escape')
  const footer = await page.locator('.status').boundingBox()
  expect(footer!.x + footer!.width).toBeLessThanOrEqual(375)
})

test('completion ripple runs once, releases its canvas and leaves the timer usable', async ({ page }, testInfo) => {
  await panel(page).getByRole('button', { name: 'Countdown', exact: true }).click()
  await page.getByLabel('Minutes', { exact: true }).fill('0')
  await page.getByLabel('Seconds', { exact: true }).fill('1')
  await panel(page).getByRole('button', { name: 'Start', exact: true }).click()
  await page.clock.runFor(1100)
  await expect(panel(page).locator('.countdown-ripple')).toHaveCount(1)
  await expect(page.locator('.timer-completion')).toHaveText('Time’s up')
  await page.clock.runFor(500)
  await page.screenshot({ path: testInfo.outputPath('countdown-ripple.png') })
  await page.clock.runFor(2400)
  await expect(page.locator('.countdown-ripple')).toHaveCount(0)
  await panel(page).getByRole('button', { name: 'Reset', exact: true }).click()
  await expect(panel(page).getByRole('button', { name: 'Start', exact: true })).toBeEnabled()
})

test('reduced motion skips completion graphics', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await panel(page).getByRole('button', { name: 'Countdown', exact: true }).click()
  await page.getByLabel('Minutes', { exact: true }).fill('0')
  await page.getByLabel('Seconds', { exact: true }).fill('1')
  await panel(page).getByRole('button', { name: 'Start', exact: true }).click()
  await page.clock.runFor(1100)
  await expect(page.locator('.timer-completion')).toHaveText('Time’s up')
  await expect(page.locator('.countdown-ripple')).toHaveCount(0)
})

test('WebGL unavailability leaves countdown completion intact', async ({ page }) => {
  await page.evaluate(() => {
    const original = HTMLCanvasElement.prototype.getContext
    HTMLCanvasElement.prototype.getContext = function (...args: Parameters<typeof original>) {
      if (args[0] === 'webgl') return null
      return original.apply(this, args)
    } as typeof original
  })
  await panel(page).getByRole('button', { name: 'Countdown', exact: true }).click()
  await page.getByLabel('Minutes', { exact: true }).fill('0')
  await page.getByLabel('Seconds', { exact: true }).fill('1')
  await panel(page).getByRole('button', { name: 'Start', exact: true }).click()
  await page.clock.runFor(1100)
  await expect(page.locator('.timer-completion')).toHaveText('Time’s up')
  await expect(page.locator('.countdown-ripple')).toHaveCount(0)
  await panel(page).getByRole('button', { name: 'Reset', exact: true }).click()
  await expect(panel(page).getByRole('button', { name: 'Start', exact: true })).toBeEnabled()
})

test('on a phone, completion is a dismissible banner above a single-row footer', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 740 })
  await panel(page).getByRole('button', { name: 'Countdown', exact: true }).click()
  await page.getByLabel('Minutes', { exact: true }).fill('0')
  await page.getByLabel('Seconds', { exact: true }).fill('1')
  await panel(page).getByRole('button', { name: 'Start', exact: true }).click()
  await page.keyboard.press('Escape')
  await page.clock.fastForward(5000)
  const banner = page.locator('.timer-completion-row')
  await expect(banner).toBeVisible()
  await expect(banner.locator('.timer-completion')).toHaveText('Time’s up')
  const centre = (box: { y: number; height: number } | null) => box!.y + box!.height / 2
  const bannerBox = await banner.boundingBox()
  const dot = await page.locator('.status-dot').boundingBox()
  const controls = await page.locator('.status button:visible:not(.timer-dismiss)').evaluateAll(buttons => buttons.map(b => Math.round(b.getBoundingClientRect().top + b.getBoundingClientRect().height / 2)))
  // Every footer control shares one row below the banner, and the storage dot centres on it.
  expect(Math.max(...controls) - Math.min(...controls)).toBeLessThanOrEqual(1)
  expect(bannerBox!.y + bannerBox!.height).toBeLessThanOrEqual(controls[0])
  expect(Math.abs(centre(dot) - (await page.locator('.format-button').evaluate(el => el.getBoundingClientRect().top + el.getBoundingClientRect().height / 2)))).toBeLessThan(1)
  await banner.getByRole('button', { name: 'Dismiss', exact: true }).click()
  await expect(banner).toHaveCount(0)
  await expect(trigger(page)).toBeFocused()
})

test('the finished banner never overflows or strands the storage dot on a very narrow phone', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 740 })
  await panel(page).getByRole('button', { name: 'Countdown', exact: true }).click()
  await page.getByLabel('Minutes', { exact: true }).fill('0')
  await page.getByLabel('Seconds', { exact: true }).fill('1')
  await panel(page).getByRole('button', { name: 'Start', exact: true }).click()
  await page.keyboard.press('Escape')
  await page.clock.fastForward(5000)
  const footer = await page.locator('.status').boundingBox()
  expect(footer!.x + footer!.width).toBeLessThanOrEqual(320)
  const dot = await page.locator('.status-dot').boundingBox()
  const format = await page.locator('.format-button').boundingBox()
  expect(Math.abs((dot!.y + dot!.height / 2) - (format!.y + format!.height / 2))).toBeLessThan(1)
})
