import { expect, test, type Page } from '@playwright/test'

const panel = (page: Page) => page.getByRole('dialog', { name: 'Timer', exact: true })
const readout = (page: Page) => panel(page).locator('.time-display')
const trigger = (page: Page) => page.getByRole('button', { name: 'Timer', exact: true })

test.beforeEach(async ({ page }) => {
  await page.goto('./')
  await expect(page.getByRole('textbox', { name: 'Text editor' })).toBeVisible()
  await page.clock.install()
  await trigger(page).click()
})

test('stopwatch continues with panel closed, pauses, resumes and resets', async ({ page }) => {
  await panel(page).getByRole('button', { name: 'Start', exact: true }).click()
  await expect(panel(page).getByRole('button', { name: 'Pause', exact: true })).toBeFocused()
  await page.clock.runFor(3200)
  await expect(readout(page)).toHaveText('00:03')
  await page.keyboard.press('Escape')
  await expect(trigger(page)).toBeFocused()
  await page.clock.runFor(5000)
  await trigger(page).click()
  await expect(readout(page)).toHaveText('00:08')
  await panel(page).getByRole('button', { name: 'Pause', exact: true }).click()
  await expect(panel(page).getByRole('button', { name: 'Resume', exact: true })).toBeFocused()
  await page.clock.runFor(3000)
  await expect(readout(page)).toHaveText('00:08')
  await panel(page).getByRole('button', { name: 'Resume', exact: true }).click()
  await page.clock.runFor(2000)
  await expect(readout(page)).toHaveText('00:10')
  await panel(page).getByRole('button', { name: 'Reset', exact: true }).click()
  await expect(readout(page)).toHaveText('00:00')
})

test('countdown uses chosen duration, resumes remaining time, and finishes while closed', async ({ page }) => {
  await panel(page).getByRole('button', { name: 'Countdown', exact: true }).click()
  await page.getByLabel('Minutes', { exact: true }).fill('0')
  await page.getByLabel('Seconds', { exact: true }).fill('10')
  await panel(page).getByRole('button', { name: 'Start', exact: true }).click()
  await page.clock.runFor(3000)
  await expect(readout(page)).toHaveText('00:07')
  await panel(page).getByRole('button', { name: 'Pause', exact: true }).click()
  await page.clock.runFor(5000)
  await expect(readout(page)).toHaveText('00:07')
  await panel(page).getByRole('button', { name: 'Resume', exact: true }).click()
  await page.keyboard.press('Escape')
  // Jump past the deadline without replaying every interval: background tabs may be throttled.
  await page.clock.fastForward(60000)
  await expect(page.locator('.timer-completion')).toBeVisible()
  await trigger(page).click()
  await expect(readout(page)).toHaveText('00:00')
  await panel(page).getByRole('button', { name: 'Reset', exact: true }).click()
  await expect(readout(page)).toHaveText('00:10')
  await expect(page.getByLabel('Seconds', { exact: true })).toBeEnabled()
  await expect(page.locator('.timer-completion')).toBeHidden()
})

test('countdown rejects zero and invalid seconds and fits on a phone', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 740 })
  await panel(page).getByRole('button', { name: 'Countdown', exact: true }).click()
  await page.getByLabel('Minutes', { exact: true }).fill('0')
  await page.getByLabel('Seconds', { exact: true }).fill('0')
  await expect(panel(page).getByRole('button', { name: 'Start', exact: true })).toBeDisabled()
  await page.getByLabel('Seconds', { exact: true }).fill('60')
  await expect(panel(page).getByRole('button', { name: 'Start', exact: true })).toBeDisabled()
  await page.getByLabel('Seconds', { exact: true }).fill('30')
  await expect(panel(page).getByRole('button', { name: 'Start', exact: true })).toBeEnabled()
  const box = await panel(page).boundingBox()
  expect(box!.x).toBeGreaterThanOrEqual(0)
  expect(box!.x + box!.width).toBeLessThanOrEqual(375)
  expect(await page.getByLabel('Minutes', { exact: true }).evaluate(el => getComputedStyle(el).fontSize)).toBe('16px')
  await page.keyboard.press('Escape')
  const footer = await page.locator('.status').boundingBox()
  expect(footer!.x + footer!.width).toBeLessThanOrEqual(375)
})
